/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.datamhsController;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hilmi
 */
public class dashboard extends javax.swing.JFrame {
    
    /**
     * Creates new form dashboard
     */    
    private datamhsController dC;
    private DefaultTableModel model;
    
    public dashboard() {
        initComponents();
        
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackgroud = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMenu1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblInputDataMhs = new javax.swing.JLabel();
        btnMenu2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Mahasiswa");
        setUndecorated(true);

        panelBackgroud.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(147, 0, 0));

        panelLogo.setBackground(new java.awt.Color(147, 0, 0));
        panelLogo.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo_Universitas_Singaperbangsa_Karawang_100x100.png"))); // NOI18N
        panelLogo.add(jLabel1);

        btnExit.setBackground(new java.awt.Color(147, 0, 0));
        btnExit.setPreferredSize(new java.awt.Dimension(25, 25));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("x");

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExitLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Aplikasi Menghitung Nilai Akhir Mahasiswa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        btnMenu1.setBackground(new java.awt.Color(255, 255, 255));
        btnMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(147, 0, 0), new java.awt.Color(147, 0, 0), new java.awt.Color(147, 0, 0), new java.awt.Color(147, 0, 0)));
        btnMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenu1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenu1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenu1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMenu1MouseReleased(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_add_book_32px_3.png"))); // NOI18N

        lblInputDataMhs.setBackground(new java.awt.Color(147, 0, 0));
        lblInputDataMhs.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblInputDataMhs.setForeground(new java.awt.Color(147, 0, 0));
        lblInputDataMhs.setText("Input Data Nilai Mahasiswa");

        javax.swing.GroupLayout btnMenu1Layout = new javax.swing.GroupLayout(btnMenu1);
        btnMenu1.setLayout(btnMenu1Layout);
        btnMenu1Layout.setHorizontalGroup(
            btnMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMenu1Layout.createSequentialGroup()
                .addGroup(btnMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnMenu1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblInputDataMhs))
                    .addGroup(btnMenu1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnMenu1Layout.setVerticalGroup(
            btnMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMenu1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInputDataMhs, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnMenu2.setBackground(new java.awt.Color(255, 255, 255));
        btnMenu2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(147, 0, 0), new java.awt.Color(147, 0, 0), new java.awt.Color(147, 0, 0), new java.awt.Color(147, 0, 0)));
        btnMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenu2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenu2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenu2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenu2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMenu2MouseReleased(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_book_32px_1.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(147, 0, 0));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(147, 0, 0));
        jLabel3.setText("Lihat Data Nilai Mahasiswa");

        javax.swing.GroupLayout btnMenu2Layout = new javax.swing.GroupLayout(btnMenu2);
        btnMenu2.setLayout(btnMenu2Layout);
        btnMenu2Layout.setHorizontalGroup(
            btnMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMenu2Layout.createSequentialGroup()
                .addGroup(btnMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnMenu2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(btnMenu2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnMenu2Layout.setVerticalGroup(
            btnMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMenu2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBackgroudLayout = new javax.swing.GroupLayout(panelBackgroud);
        panelBackgroud.setLayout(panelBackgroudLayout);
        panelBackgroudLayout.setHorizontalGroup(
            panelBackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBackgroudLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(btnMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        panelBackgroudLayout.setVerticalGroup(
            panelBackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroudLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(panelBackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenu2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu1MouseClicked
        // TODO add your handling code here:
        new inputNilaiMhs().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMenu1MouseClicked

    private void btnMenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu1MouseEntered
        // TODO add your handling code here:
        btnMenu1.setBackground(new Color(134, 0, 0));
        lblInputDataMhs.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnMenu1MouseEntered

    private void btnMenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu1MouseExited
        // TODO add your handling code here:
        btnMenu1.setBackground(new Color(255, 255, 255));
        lblInputDataMhs.setForeground(new Color(147, 0, 0));
    }//GEN-LAST:event_btnMenu1MouseExited

    private void btnMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu1MousePressed
        // TODO add your handling code here:
        btnMenu1.setBackground(new Color(122, 0, 0));
        lblInputDataMhs.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnMenu1MousePressed

    private void btnMenu1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu1MouseReleased
        // TODO add your handling code here:
        btnMenu1.setBackground(new Color(255, 255, 255));
        lblInputDataMhs.setForeground(new Color(147, 0, 0));
    }//GEN-LAST:event_btnMenu1MouseReleased

    private void btnMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu2MouseClicked
        // TODO add your handling code here:
        new dataMhs().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMenu2MouseClicked

    private void btnMenu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu2MouseEntered
        // TODO add your handling code here:
        btnMenu2.setBackground(new Color(134, 0, 0));
        jLabel3.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnMenu2MouseEntered

    private void btnMenu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu2MouseExited
        // TODO add your handling code here:
        btnMenu2.setBackground(new Color(255, 255, 255));
        jLabel3.setForeground(new Color(147, 0, 0));
    }//GEN-LAST:event_btnMenu2MouseExited

    private void btnMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu2MousePressed
        // TODO add your handling code here:
        btnMenu2.setBackground(new Color(122, 0, 0));
        jLabel3.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnMenu2MousePressed

    private void btnMenu2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu2MouseReleased
        // TODO add your handling code here:
        btnMenu2.setBackground(new Color(255, 255, 255));
        jLabel3.setForeground(new Color(147, 0, 0));
    }//GEN-LAST:event_btnMenu2MouseReleased

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel btnMenu1;
    private javax.swing.JPanel btnMenu2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblInputDataMhs;
    private javax.swing.JPanel panelBackgroud;
    private javax.swing.JPanel panelLogo;
    // End of variables declaration//GEN-END:variables
}
