/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import controllers.datamhsController;
import db.dbConnect;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Hilmi
 */
public class dataMhs extends javax.swing.JFrame {

    /**
     * Creates new form dataMhs
     */
    
    private datamhsController dC;
    private DefaultTableModel model;
    
    public dataMhs() {
        initComponents();
        
        dC = new datamhsController(this);
        model = new DefaultTableModel();
        tabelMhs.setModel(model);
        model.addColumn("Nama Mahasiswa");
        model.addColumn("NPM");
        model.addColumn("Kelas");
        model.addColumn("Nilai Kehadiran");
        model.addColumn("Nilai Tugas");
        model.addColumn("Nilai UTS");
        model.addColumn("Nilai UAS");
        model.addColumn("Nilai Akhir");
        
        tampilData();
        dC.kontrolButton();
    }
        
    private void tampilData(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        String sql = "SELECT * FROM mahasiswa";
        
        try{
            Statement stat = (Statement) dbConnect.getKoneksi().createStatement();
            ResultSet res = stat.executeQuery(sql);
            
            while(res.next()){
              Object[] hasil;
              hasil = new Object[8];
              hasil[0] = res.getString("nama");
              hasil[1] = res.getString("npm");
              hasil[2] = res.getString("kelas");
              hasil[3] = res.getString("nilai_absen");
              hasil[4] = res.getString("nilai_tugas");
              hasil[5] = res.getString("nilai_uts");
              hasil[6] = res.getString("nilai_uas");
              hasil[7] = res.getString("nilai_akhir");
              
              model.addRow(hasil);
            }
        } catch (SQLException ex) {
            Logger.getLogger(dataMhs.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    
    public void ambilDataTabel(){
        int index = tabelMhs.getSelectedRow();
        
        String nama = String.valueOf(tabelMhs.getValueAt(index, 0));
        String npm = String.valueOf(tabelMhs.getValueAt(index, 1));
        String nAbsen = String.valueOf(tabelMhs.getValueAt(index, 3));
        String nTugas = String.valueOf(tabelMhs.getValueAt(index, 4));
        String nUts = String.valueOf(tabelMhs.getValueAt(index, 5));
        String nUas = String.valueOf(tabelMhs.getValueAt(index, 6));
        String nAkhir = String.valueOf(tabelMhs.getValueAt(index, 7));
        
        tfNamaMhsView.setText(nama);
        tfNpmView.setText(npm);
        tfNabsenView.setText(nAbsen);
        tfNtugasView.setText(nTugas);
        tfNutsView.setText(nUts);
        tfNuasView.setText(nUas);
        tfNakhirView.setText(nAkhir);
        
        dC.kontrolButtonDua();
    }
    
    public JTextField getNpmView(){
        return tfNpmView;
    }
    
    public JTextField getNamaMhsView(){
        return tfNamaMhsView;
    }
    
    public JTextField getNabsenView(){
        return tfNabsenView;
    }
    
    public JTextField getNtugasView(){
        return tfNtugasView;
    }
    
    public JTextField getNutsView(){
        return tfNutsView;
    }
    
    public JTextField getNuasView(){
        return tfNuasView;
    }
    
    public JTextField getNakhirView(){
        return tfNakhirView;
    }
    
    
    public JPanel getTombolUpdate(){
        return btnUpdate;
    }
    
    public JPanel getTombolHapus(){
        return btnHapus;
    }
    
    public JPanel getTombolBatal(){
        return btnBatal;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMhs = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JPanel();
        lblSimpan1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNamaMhsView = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfNpmView = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfNabsenView = new javax.swing.JTextField();
        tfNtugasView = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfNutsView = new javax.swing.JTextField();
        tfNuasView = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JPanel();
        lblSimpan2 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JPanel();
        lblReset1 = new javax.swing.JLabel();
        btnHitung = new javax.swing.JPanel();
        lblReset2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfNakhirView = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(766, 516));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(629, 475));

        tabelMhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Mahasiswa", "NPM", "Kelas", "Nilai Kehadiran", "Nilai Tugas", "Nilai UTS", "Nilai UAS", "Nilai Akhir"
            }
        ));
        tabelMhs.setFocusable(false);
        tabelMhs.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelMhs.setRowHeight(25);
        tabelMhs.setShowVerticalLines(false);
        tabelMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMhs);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(142, 0, 0));
        jLabel12.setText("Data Mahasiswa");

        btnHapus.setBackground(new java.awt.Color(147, 0, 0));
        btnHapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(188, 0, 0), new java.awt.Color(188, 0, 0), new java.awt.Color(188, 0, 0), new java.awt.Color(188, 0, 0)));
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHapusMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHapusMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHapusMouseReleased(evt);
            }
        });

        lblSimpan1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblSimpan1.setForeground(new java.awt.Color(255, 255, 255));
        lblSimpan1.setText("Hapus");

        javax.swing.GroupLayout btnHapusLayout = new javax.swing.GroupLayout(btnHapus);
        btnHapus.setLayout(btnHapusLayout);
        btnHapusLayout.setHorizontalGroup(
            btnHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHapusLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lblSimpan1)
                .addGap(24, 24, 24))
        );
        btnHapusLayout.setVerticalGroup(
            btnHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHapusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSimpan1)
                .addContainerGap())
        );

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setPreferredSize(new java.awt.Dimension(25, 25));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        btnBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_left_32px_1.png"))); // NOI18N
        btnBack.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(142, 0, 0));
        jLabel4.setText("Nama Mahasiswa");

        tfNamaMhsView.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tfNamaMhsView.setForeground(new java.awt.Color(142, 0, 0));
        tfNamaMhsView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(142, 0, 0));
        jLabel5.setText("NPM");

        tfNpmView.setEditable(false);
        tfNpmView.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tfNpmView.setForeground(new java.awt.Color(142, 0, 0));
        tfNpmView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(142, 0, 0));
        jLabel7.setText("Nilai Kehadiran");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(142, 0, 0));
        jLabel8.setText("Nilai Tugas");

        tfNabsenView.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tfNabsenView.setForeground(new java.awt.Color(142, 0, 0));
        tfNabsenView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0)));

        tfNtugasView.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tfNtugasView.setForeground(new java.awt.Color(142, 0, 0));
        tfNtugasView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(142, 0, 0));
        jLabel9.setText("Nilai UTS");

        tfNutsView.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tfNutsView.setForeground(new java.awt.Color(142, 0, 0));
        tfNutsView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0)));

        tfNuasView.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tfNuasView.setForeground(new java.awt.Color(142, 0, 0));
        tfNuasView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(142, 0, 0));
        jLabel10.setText("Niali UAS");

        btnUpdate.setBackground(new java.awt.Color(147, 0, 0));
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(188, 0, 0), new java.awt.Color(188, 0, 0), new java.awt.Color(188, 0, 0), new java.awt.Color(188, 0, 0)));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUpdateMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnUpdateMouseReleased(evt);
            }
        });

        lblSimpan2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblSimpan2.setForeground(new java.awt.Color(255, 255, 255));
        lblSimpan2.setText("Update");

        javax.swing.GroupLayout btnUpdateLayout = new javax.swing.GroupLayout(btnUpdate);
        btnUpdate.setLayout(btnUpdateLayout);
        btnUpdateLayout.setHorizontalGroup(
            btnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnUpdateLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lblSimpan2)
                .addGap(20, 20, 20))
        );
        btnUpdateLayout.setVerticalGroup(
            btnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSimpan2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBatal.setBackground(new java.awt.Color(255, 255, 255));
        btnBatal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(188, 0, 0), new java.awt.Color(188, 0, 0), new java.awt.Color(188, 0, 0), new java.awt.Color(188, 0, 0)));
        btnBatal.setForeground(new java.awt.Color(180, 0, 0));
        btnBatal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBatalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBatalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBatalMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBatalMouseReleased(evt);
            }
        });

        lblReset1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblReset1.setForeground(new java.awt.Color(188, 0, 0));
        lblReset1.setText("Batal");

        javax.swing.GroupLayout btnBatalLayout = new javax.swing.GroupLayout(btnBatal);
        btnBatal.setLayout(btnBatalLayout);
        btnBatalLayout.setHorizontalGroup(
            btnBatalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBatalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblReset1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnBatalLayout.setVerticalGroup(
            btnBatalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBatalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReset1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnHitung.setBackground(new java.awt.Color(255, 255, 255));
        btnHitung.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(188, 0, 0), new java.awt.Color(188, 0, 0), new java.awt.Color(188, 0, 0), new java.awt.Color(188, 0, 0)));
        btnHitung.setForeground(new java.awt.Color(180, 0, 0));
        btnHitung.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnHitung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHitungMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHitungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHitungMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHitungMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHitungMouseReleased(evt);
            }
        });

        lblReset2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblReset2.setForeground(new java.awt.Color(188, 0, 0));
        lblReset2.setText("Hitung");

        javax.swing.GroupLayout btnHitungLayout = new javax.swing.GroupLayout(btnHitung);
        btnHitung.setLayout(btnHitungLayout);
        btnHitungLayout.setHorizontalGroup(
            btnHitungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHitungLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lblReset2)
                .addGap(29, 29, 29))
        );
        btnHitungLayout.setVerticalGroup(
            btnHitungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHitungLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReset2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(142, 0, 0));
        jLabel13.setText("Nilai Akhir");

        tfNakhirView.setEditable(false);
        tfNakhirView.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tfNakhirView.setForeground(new java.awt.Color(142, 0, 0));
        tfNakhirView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0), new java.awt.Color(142, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258)
                .addComponent(jLabel12)
                .addContainerGap(310, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(184, 184, 184))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNpmView)
                                    .addComponent(tfNabsenView)
                                    .addComponent(tfNamaMhsView, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNuasView, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(tfNtugasView, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(tfNutsView, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfNakhirView, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(476, 476, 476)
                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNamaMhsView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(tfNtugasView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNpmView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(tfNutsView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNakhirView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNabsenView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNuasView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))))
                    .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        // TODO add your handling code here:
        dC.hapus();
        tampilData();
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseEntered
        // TODO add your handling code here:
        btnHapus.setBackground(new Color(134, 0, 0));
    }//GEN-LAST:event_btnHapusMouseEntered

    private void btnHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseExited
        // TODO add your handling code here:
        btnHapus.setBackground(new Color(147, 0, 0));
    }//GEN-LAST:event_btnHapusMouseExited

    private void btnHapusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMousePressed
        // TODO add your handling code here:
        btnHapus.setBackground(new Color(122, 0, 0));
    }//GEN-LAST:event_btnHapusMousePressed

    private void btnHapusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseReleased
        // TODO add your handling code here:
        btnHapus.setBackground(new Color(147, 0, 0));
    }//GEN-LAST:event_btnHapusMouseReleased

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
         btnUpdate.setBackground(new Color(134, 0, 0));
         dC.update();
         tampilData();
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        // TODO add your handling code here:
        btnUpdate.setBackground(new Color(134, 0, 0));
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        // TODO add your handling code here:
         btnUpdate.setBackground(new Color(147, 0, 0));
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnUpdateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMousePressed
        // TODO add your handling code here:
        btnUpdate.setBackground(new Color(122, 0, 0));
    }//GEN-LAST:event_btnUpdateMousePressed

    private void btnUpdateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseReleased
        // TODO add your handling code here:
        btnUpdate.setBackground(new Color(147, 0, 0));
    }//GEN-LAST:event_btnUpdateMouseReleased

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        new dashboard().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        // TODO add your handling code here:
        dC.kontrolButton();
        dC.bersihkan1();
    }//GEN-LAST:event_btnBatalMouseClicked

    private void btnBatalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalMouseEntered

    private void btnBatalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalMouseExited

    private void btnBatalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalMousePressed

    private void btnBatalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalMouseReleased

    private void tabelMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMhsMouseClicked
        // TODO add your handling code here:
        ambilDataTabel();
    }//GEN-LAST:event_tabelMhsMouseClicked

    private void btnHitungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHitungMouseClicked
        // TODO add your handling code here:
        double nabsen = Double.parseDouble(tfNabsenView.getText());
        double ntugas = Double.parseDouble(tfNtugasView.getText());
        double nuas = Double.parseDouble(tfNutsView.getText());
        double nuts = Double.parseDouble(tfNuasView.getText());

        double nakhir = (double) ((nabsen * 0.1) + (ntugas * 0.2)
            + (nuts * 0.3) + (nuas * 0.4));

        tfNakhirView.setText(String.valueOf(nakhir));
    }//GEN-LAST:event_btnHitungMouseClicked

    private void btnHitungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHitungMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHitungMouseEntered

    private void btnHitungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHitungMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHitungMouseExited

    private void btnHitungMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHitungMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHitungMousePressed

    private void btnHitungMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHitungMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHitungMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataMhs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBack;
    private javax.swing.JPanel btnBatal;
    private javax.swing.JPanel btnHapus;
    private javax.swing.JPanel btnHitung;
    private javax.swing.JPanel btnUpdate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblReset1;
    private javax.swing.JLabel lblReset2;
    private javax.swing.JLabel lblSimpan1;
    private javax.swing.JLabel lblSimpan2;
    private javax.swing.JTable tabelMhs;
    private javax.swing.JTextField tfNabsenView;
    private javax.swing.JTextField tfNakhirView;
    private javax.swing.JTextField tfNamaMhsView;
    private javax.swing.JTextField tfNpmView;
    private javax.swing.JTextField tfNtugasView;
    private javax.swing.JTextField tfNuasView;
    private javax.swing.JTextField tfNutsView;
    // End of variables declaration//GEN-END:variables
}
